import './globals.css'
import { Inter } from 'next/font/google'
import 'mdbootstrap/css/bootstrap.min.css';
import 'mdbootstrap/css/mdb.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quick serve',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
